services:
  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=192.168.0.137,1433;Database=EmployeeDb;User Id=Thembinkosi;Password=Themba1234;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - PORT=80
      - JwtSection__Key=9f2b8e3c9f47a43b37ab78e192adfcd14c828432ee3e78b3d3b9b3494ad0b6db
      - JwtSection__Issuer=https://localhost:7179
      - JwtSection__Audience=https://localhost:7179
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: Client/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network
    depends_on:
      - server

networks:
  app-network:
    driver: bridge